<?php
require_once("core.php");
requireLogin();

allowSuperiorOnly($current_role);

$pageTitle = "Email Logs";
renderPageHeader($pageTitle);

$sql = "SELECT e.*, l.status, s.staff_name
        FROM email_log e
        INNER JOIN leave_application l ON e.leave_id = l.leave_id
        INNER JOIN staff s ON l.staff_id = s.staff_id";
$types = "";
$params = array();

if ($current_role == "superior") {
    $sql .= " WHERE s.superior_id = ?";
    $types = "i";
    $params[] = $current_staff_id;
}

$sql .= " ORDER BY e.email_id DESC";
$emailRows = dbSelectAll($conn, $sql, $types, $params);
?>

<div class="card">
    <h3>Email Notification Records</h3>
    <p class="help-text">
        This page records the approval or rejection email content generated by the system.
    </p>

    <table class="table">
        <tr>
            <th>Email ID</th>
            <th>Leave ID</th>
            <th>Staff Name</th>
            <th>Receiver Email</th>
            <th>Subject</th>
            <th>Message</th>
            <th>Send Date</th>
        </tr>

        <?php if (count($emailRows) > 0) { ?>
            <?php foreach ($emailRows as $row) { ?>
                <tr>
                    <td><?php echo e($row["email_id"]); ?></td>
                    <td><?php echo e($row["leave_id"]); ?></td>
                    <td><?php echo e($row["staff_name"]); ?></td>
                    <td><?php echo e($row["receiver_email"]); ?></td>
                    <td><?php echo e($row["subject"]); ?></td>
                    <td><?php echo e($row["message"]); ?></td>
                    <td><?php echo e($row["send_date"]); ?></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td colspan="7">No email log found.</td>
            </tr>
        <?php } ?>
    </table>
</div>

<?php renderPageFooter(); ?>
